"""Changed fields for user model

Revision ID: 48500bc00458
Revises: 84770b9b52b3
Create Date: 2025-02-26 07:21:21.737160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48500bc00458'
down_revision = '84770b9b52b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('email', sa.String(length=320), nullable=False))
        batch_op.alter_column('password',
                              existing_type=sa.VARCHAR(length=250),
                              type_=sa.String(length=128),
                              existing_nullable=False)
        batch_op.create_unique_constraint('uq_users_email', ['email'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('username', sa.VARCHAR(length=250), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
                              existing_type=sa.String(length=128),
                              type_=sa.VARCHAR(length=250),
                              existing_nullable=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
